
version: "2.1"

services:

  database:
    container_name: "mongodb"
    image: "mongo:4.2.3"
    restart: always
    networks:
      - network_private
    volumes:
      - database-data:/data/db
    expose:
      - "27017"

  markdown_blog:
    container_name: "markdown-blog"
    image: "xxlabaza/markdown-blog"
    restart: always
    build: ./
    depends_on:
      - database
    environment:
      - SERVER_PORT=5000
      - DATABASE_HOST=database
    networks:
      - network_private
      - network_public
    expose:
      - "5000"
    ports:
      - "5000:5000"

networks:
  network_private:
    internal: true
  network_public:
    internal: false

volumes:
  database-data:
